### ISSUE TITLE
Add support for background videos

### ISSUE THREAD

**Issue by zachgibson** [zachgibson/react-native-parallax-swiper#1]
Like Twitter Moments.

**Comment by brianhiss** [comment]
Hey @zachgibson, any progress on this? Saw your [tweet](https://twitter.com/zacharykeith_/status/907632467296874498), it looks like you've integrated video.

Love the progress indicator on the bottom as well, subtle, but very clean.

Will you be contributing back those changes? I submitted a pull request to update the library for use with react-native 0.48.0+.

**Comment by zachgibson** [comment]
Those are actually GIFs, which already work. However I did use videos for the Vevo example in the README and realized it might be a bit of a pain to try and add video support in the current version. I’m working on a new API that allows passing of whole components for background/foreground content which I think will be better because it gives much more flexibility for user-controlled components. e.g. Video.

You know you mentioning the progress indicator makes me think that might be a useful addition to this component. What do you think?

**Comment by brianhiss** [comment]
Not sure if you already used it, or would want to add a dependency for video, but I've had good luck using [react-native-video](https://github.com/react-native-community/react-native-video).

The progress indicator does look pretty smooth from your GIF!

**Comment by zachgibson** [comment]
Yeah I’ve used react-native-video. I’m not sure I want to manage handling that component through react-native-parallax-swiper tho. I feel it would be better to let the user manage this.

With the new API I’m experimenting with, implementing Video could look like this:
```javascript
<ParallaxSwiper>
  <ParallaxSwiper.Page
    foregroundContent={<PlayButton ...props />}
    backgroundContent={<Video ...props />}
  />
</ParallaxSwiper>
```

So video logic is handled by the user.

**Comment by brianhiss** [comment]
That API seems like the best way forward. Would be good to use components like react-native-video and Lottie as well for animations.

Let me know if you want me to test anything, or run ideas by.

**Comment by zachgibson** [comment]
For sure. This new API along with `onMomentumScrollEnd` which contains active index and `animatedScrollValue` you can achieve some really cool effects. I have a lot of ideas for this. (Just learned you can play Lottie animations based on scroll 😬).

And thanks man! There hasn’t been much collaboration on this so it’s nice to have someone else who is interested and willing to collaborate.

**Comment by zachgibson** [comment]
@brianhiss Yo! I finally finished working through some [new API](https://github.com/zachgibson/react-native-parallax-swiper/tree/feature/allow-background-and-foreground-component-injection) ideas. I’d love to hear any feedback or thoughts you might have.

**Comment by brianhiss** [comment]
@zachgibson I'll take a look and get back to you. Happy Thanksgiving!

**Comment by brianhiss** [comment]
@zachgibson I'm low on time right now, but I took a look and it's looking good. Are you going to create some demos of the gif's you have up there? I see you have that in your README, but didn't know if that was still on your agenda.

**Comment by zachgibson** [comment]
@brianhiss Yeah forsure, I’ll create some demos. I wanted to get your input API wise before I published. I feel pretty good about it. I think it sets a necessary constraint with `ParallaxSwiperPage` and makes rendering UI more flexible by allowing arbitrary component rendering versus very specific props to handle specific situations. e.g. `backgroundImage`

Now you can easily add something like react-native-video and handle state and props yourself, as `ParallaxSwiper` doesn’t need to know any of this.

**Comment by zachgibson** [comment]
@brianhiss Hey man so I finally got everything to a point to merge! I have two of the three GIF examples now. Still need to add some more and cleanup the existing example code, but for now you can totally dig through them and see how to use something like `react-native-video`. 👍

**Comment by brianhiss** [comment]
@zachgibson I'll take a look. Just got back from a vacation, saw all your emails. I'll try and dig in soon! Great stuff..

**Comment by zachgibson** [comment]
This enhancement is added in [v1.0.0](https://github.com/zachgibson/react-native-parallax-swiper/tree/v1.0.0) 🎉
