### ISSUE TITLE
Can't run example/demo

### ISSUE THREAD

**Issue by bobmulder** [zachgibson/react-native-parallax-swiper#14]
I'm trying to run the example, but get the following error: `Failed to load bundle [...] Unable to resolve module 'react' from '[path]' [...]: Module does not exist in the module map.`

I did everthing the docs told me to do:
```
$ npm install
$ react-native link
$ react-native run-ios
```

**Comment by bobmulder** [comment]
Fixed by installing the library through NPM instead of a local file. This should be fixed soon by @zachgibson.

**Comment by zachgibson** [comment]
Fixed with [v1.1.3](https://github.com/zachgibson/react-native-parallax-swiper/releases/tag/v1.1.3)! Thanks @bobmulder for helping me track this down.
