### ISSUE TITLE
ISSUE WITH MODAL

### ISSUE THREAD

**Issue by Pfurr** [zachgibson/react-native-parallax-swiper#17]
I'm working with modals and parallax swiper but it not work.  I added a different modal to each screen of Parallax Swiper Page (3 screens, for now) and it always returns the first modal of the first screen of Parallax swiper. I would like to print a different modal for each screen. Any suggestions?

**Comment by zachgibson** [comment]
Can you create an Expo snack or post your code? Not sure what the issue is without seeing your code.

**Comment by Pfurr** [comment]
I am attaching a file with code
 @zachgibson

**Comment by zachgibson** [comment]
@pherm Did you mean to close this? Sorry for the delay. If you’re still having this issue let me know and I’ll run your demo and see what’s going on.

**Comment by Pfurr** [comment]
@zachgibson I still have the issue, can you verify?

**Comment by Pfurr** [comment]
@zachgibson why do you close this issue without a solution?? Man, you're not serious

**Comment by zachgibson** [comment]
@pherm I didn’t close it. Look above, it says you did. Also you sent me a text file without a package.json or other component files (RoundedButton) so I can’t even run your demo.

**Comment by Pfurr** [comment]
@zachgibson man,  I wrote three days ago: '' I still have the issue, can you verify?''. But never mind. I will solve the problem differently.

**Comment by zachgibson** [comment]
Dude your facts are off. You said that 2 days ago. You barely put any effort into helping me reproduce your issue. I want to help, but keep in mind this is open source and I do it for free. I have a full-time job and other responsibilities. Weekends for me is when I get time to look at stuff like this.

**Comment by Pfurr** [comment]
No man, you're not understand. 

1. **I've reported a potential bug because I've met it.** 
2. in my case they are 3 business days. I live in EU.
3. you are not obliged to help anyone. But if you don't have time or other stuff tell me it immediately (developers work with oss).
4. I don't have time like you to wait. I'm working. For me it's much more convenient to find other solutions (with a other node package for example) then to wait your feedback. And i don't have any problem with you, anyway I speak blunt. Time is money for all.

**Comment by zachgibson** [comment]
I’m off work for the weekend and I have time to look into this for you if you want. Just give me a repo or Expo snack so I can easily reproduce your issue and see what’s going on.
