### ISSUE TITLE
ScrollToIndex does not call onMomentumScrollEnd

### ISSUE THREAD

**Issue by gabgagnon** [zachgibson/react-native-parallax-swiper#22]
By reading the definition of those props, Should ScrollToIndex calls onMomentumScrollEnd when the automatic scroll is over?

Thanks you

**Comment by zachgibson** [comment]
Yes, `onMomentumScrollEnd` occurs as the ScrollView glides to a stop, and `scrollToIndex` just scrolls the ScrollView for you.

**Comment by abhi06991** [comment]
Once `onMomentumScrollEnd` is fired, I want to fetch more datas and add it to the list. Is this possible ? If its possible, will the entire component re-render? How will be the performance?

**Comment by zachgibson** [comment]
@abhi06991 Not sure, this component just abstracts React Native’s ScrollView component. Also using FlatList is on the roadmap which will improve long lists.

**Comment by mohity777** [comment]
Any solution ?? I am using react native flatlist and this is happening to me.
