### ISSUE TITLE
ParallaxSwiper Props Height

### ISSUE THREAD

**Issue by yedeba** [zachgibson/react-native-parallax-swiper#23]
Hi, is possible height control of ParallaxSwiper?
Thanks

**Comment by zachgibson** [comment]
Yes you can, just put `ParallaxSwiper` in a container and size it accordingly, it will fill its container. I might end up adding these as props.

e.g.
```JSX
<View style={{ width: 200, height: 400 }}>
  <ParallaxSwiper>
    ...
  </ParallaxSwiper>
</View>
```
