### ISSUE TITLE
There's some props to add a pagination for UX like dots pagination or bar pagination?

### ISSUE THREAD

**Issue by flixyudh** [zachgibson/react-native-parallax-swiper#27]

**Comment by zachgibson** [comment]
There’s nothing by default. You can easily do this yourself with what this component exposes. But this might be a good idea to do in the future.

**Comment by flixyudh** [comment]
Actually, I'm not good enough with `React Native (Javascript)`, 
Mind if you add this feature on the next update?
Just to let user know how much images available to swipe

**Comment by zachgibson** [comment]
@zxccvvv I will play around with this idea. I’m not sure if it fits with the pattern I’m following with this UI—usually you don’t see paginated dots but it might work.
