### ISSUE TITLE
With more then 100 image in background it taking too much time to load even some images are not showing.

### ISSUE THREAD

**Issue by ShaileshPrajapati-BTC** [zachgibson/react-native-parallax-swiper#29]

**Comment by zachgibson** [comment]
@ShaileshPrajapati-BTC Yes this is expected. We need to use `FlatList` to improve perf on larger lists. See [the FlatList item is unchecked](https://github.com/zachgibson/react-native-parallax-swiper#todo) in TODO list. I will hopefully be working on this soon.
