### ISSUE TITLE
Question: Plans to Add Rest of Scroll View Props?

### ISSUE THREAD

**Issue by Jmeza081** [zachgibson/react-native-parallax-swiper#30]
Thanks again for the awesome library! I was looking into a (bug, but not really) yesterday in which embedding a set of `TextInput`s in a `ParallaxSwiperPage` would cause some semi-unexpected behavior on Android:

- If one `TextInput` is focused and the keyboard is open, switching to another `TextInput` on the same page closes the keyboard and you are forced to tap it again to focus the input. 

Adding the prop `keyboardShouldPersistTaps={'always'}` to your `ParallaxSwiper.js`'s `ScrollView` fixes the issue. I was wondering if there were still plans to expose the rest of the `ScrollView` props and making this prop optional, or if you were planning on taking the repo in a different direction?

**Comment by zachgibson** [comment]
Hey @Jmeza081! Yeah I’m wondering if simply spreading props would work well. I believe so. Totally open to PRs too. 😉

**Comment by Jmeza081** [comment]
Gotcha! Just out of curiosity, what is the reasoning behind not adding `{...this.props}` to the `ScrollView` to allow the rest of the supplied props to pass through your component? Will it mess with props your Swiper is handling internally? If it will, a simple PR for `keyboardShouldPersistTaps` will have to suffice when I get around to it.

**Comment by zachgibson** [comment]
@Jmeza081 I briefly tried this but it broke something else. This is definitely on my list to work on soon.

**Comment by zachgibson** [comment]
Closing in favor of #33.
