### ISSUE TITLE
Screen orientation half swipe

### ISSUE THREAD

**Issue by gds3k3** [zachgibson/react-native-parallax-swiper#31]
Hello, great component! Many thanks!

I have a little problem when screen orientation changes. Swipe page appears half swiped.
This happens when screen orientation changes and the current swipe page is some of middle pages, first and last pages shows correctly.

I changed pages order, to test whether the problem is on some particular content, but same result.

Thanks again.

**Comment by umerbaig** [comment]
same issue happing with me

**Comment by zachgibson** [comment]
Hey @gds3k3 and @umerbaig 👋 

I haven’t done any work to support landscape orientation so I’m not surprised to hear this. The widths are set initially so the ScrollView knows when to snap, e.g. every 300px, this feature enables the divider views. So the width would need to update on orientation change.

**Comment by zachgibson** [comment]
Closing in favor of #32.
