### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by calacianu** [zachgibson/react-native-parallax-swiper#38]
I try to use the carousel with react native 0.59.8, is not loading. I get the following error in debugger
`{
type: "InternalError",
errors: [ ],
message: "Metro Bundler has encountered an internal error, please check your terminal error output for more details"
}`

After I remove the carousel, it works fine. I used your example, copy/paste.

Thank you!

**Comment by zachgibson** [comment]
@calacianu Just created a new React Native project @0.59.8 and copied/pasted my example code and everything works just fine. What device are you running it on?

**Comment by calacianu** [comment]
Hey! Thank you for your reply, I'll try again and see. I'm using ios simulator :)

**Comment by zachgibson** [comment]
@calacianu Sure thing. 🙂 Feel free to re-open this issue if you are still experiencing it.
